const sequelize = require('../bin/sequelize')
require('./course')
require('./courseItem')
require('./user')
require('./news')
require('./download')
require('./admin')
require('./order')
require('./parper')
require('./parperOption')
require('./parperRecord')
module.exports = sequelize;
