<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    <meta charset="utf-8">
    <title>鹏程教育在线学习系统</title>
    <meta name="keywords" content="在线学习系统">
    <meta name="description" content="在线学习系统">
    <link href="/static/css/style.css" rel="stylesheet"/>
    <link href="/static/css/animate.min.css" rel="stylesheet"/>
    <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico"/>
    <!--[if lte IE 9]>
    <script src="/static/js/html5shiv.min.js"></script>
    <![endif]-->
    <script src="/static/js/jquery-1.8.3.min.js"></script>
    <script src="/static/js/fastclick.js"></script>
    <script src="/static/js/wow.min.js"></script>
    <script src="/static/js/common.js"></script>
</head>
<body>