require('./home')
require('./api')
require('./login')
require('./learn/index')
require('./learn/course')
require('./learn/account')
require('./learn/exam')
require('./learn/info')
require('./learn/train')

require('./course/index')
require('./info/index')
require('./help/index')
require('./rank/index')
require('./download/index')
require('./paper/index')
